version: 3

vars:
  VERSION: v0.0.1
  BIN_DIR: "bin"
  ASSET_DIR: "assets"
  UI_SRC_YAML: "ui.yaml"
  UI_DIST_JSON: "ui.json"

tasks:
  jj-st:
    desc: "Run jj st"
    cmds:
      - jj st

  convert:
    desc: "run convert"
    cmds:
      - go run ./cmd/converter

  build:
    desc: "Build"
    deps:
      - jj-st
    sources:
      - ./script/*.go
      - ./builtin/*.go
      - ./yamlui/*.go
      - ./cmd/**/*.go
    generates:
      - "{{.BIN_DIR}}/main"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BIN_DIR}}/main --tags debug ./cmd/test1

  run:
    desc: "Run"
    deps:
      - build
      - convert
    cmds:
      - "{{.BIN_DIR}}/main"

  convert:
    desc: "Convert"
    sources:
      - "{{.ASSET_DIR}}/{{.UI_SRC_YAML}}"
    generates:
      - "{{.BIN_DIR}}/{{.UI_DIST_JSON}}"
    cmds:
      - cat {{.ASSET_DIR}}/{{.UI_SRC_YAML}} | yq -o=json > {{.BIN_DIR}}/{{.UI_DIST_JSON}}

  test:
    desc: "Test"
    sources:
      - ./script/*.go
      - ./builtin/*.go
      - ./yamlui/*.go
    cmds:
      - go test -v ./...


  clean:
    desc: "Clean"
    cmds:
      - "rm -rf {{.BIN_DIR}}/main"

  tag:
    desc: "タグを更新する"
    deps:
      - build
    cmds:
      - git tag {{.VERSION}}
      - git tag

  default:
    cmds:
      - task --list

